###############################################################################
# staging.ini — Inventaire Ansible Staging (développement)
###############################################################################

[webservers]
srvstg-web01 ansible_host=192.168.1.10

[appservers]
srvstg-app01 ansible_host=192.168.1.20 websphere_node=node01

[dbservers]
srvstg-db01 ansible_host=192.168.1.30 pg_role=primary

[batchservers]
srvstg-batch01 ansible_host=192.168.1.40

[k8s_masters]
srvstg-k8s-master01 ansible_host=192.168.1.50

[k8s_workers]
srvstg-k8s-worker01 ansible_host=192.168.1.51

[monitoring]
srvstg-mon01 ansible_host=192.168.1.60

[staging:children]
webservers
appservers
dbservers
batchservers
k8s_masters
k8s_workers
monitoring

[staging:vars]
env=staging
domain=bankops.internal.stg
